export function createMockToday() {
  return {
    workspace: {
      id: "mock-workspace",
      name: "Personal workspace",
      userDisplayName: "Brandon",
      userInitials: "BM",
      timezone: "America/Los_Angeles",
    },
    activeProjectId: "device-mcp",
    beeLive: true,
    projects: [
      {
        id: "product-forge",
        name: "Product Forge",
        phase: "Implementation",
        phaseTone: "healthy",
        updated: "2 hours ago",
        latestChange: "Added auth middleware and updated tests",
        milestone: "Beta release (v0.2)",
        milestoneTiming: "in 4 days",
        blocker: "None",
        blockerTone: "healthy",
        worker: "Codex",
        workerState: "Running (Vercel)",
        color: "amber",
      },
      {
        id: "device-mcp",
        name: "Device MCP",
        phase: "Design",
        phaseTone: "active",
        updated: "1 day ago",
        latestChange: "Finalized MCP schema for device telemetry",
        milestone: "MVP integration",
        milestoneTiming: "in 1 week",
        blocker: "1 blocker",
        blockerTone: "danger",
        worker: "Claude",
        workerState: "Idle",
        color: "blue",
      },
      {
        id: "monroe-eve",
        name: "Monroe Eve",
        phase: "Research",
        phaseTone: "neutral",
        updated: "6 hours ago",
        latestChange: "Ingest pipeline performance improved",
        milestone: "Private alpha",
        milestoneTiming: "in 2 weeks",
        blocker: "None",
        blockerTone: "healthy",
        worker: "GPT-5",
        workerState: "Idle",
        color: "slate",
      },
    ],
    priorities: [
      {
        id: "priority-product-forge",
        group: "Deep Work",
        time: "9:00 AM – 11:00 AM",
        title: "Finish Product Forge onboarding flow",
        detail: "Complete error states and polish copy. Ship ready for internal beta.",
        project: "Product Forge",
        tone: "amber",
        completed: false,
      },
      {
        id: "priority-device-mcp",
        group: "Project Progress",
        time: "11:00 AM – 1:00 PM",
        title: "Review Device MCP sandbox results",
        detail: "Assess changes, run locally, and provide feedback.",
        project: "Device MCP",
        tone: "teal",
        completed: false,
      },
      {
        id: "priority-messages",
        group: "Communication",
        time: "2:00 PM – 3:00 PM",
        title: "Respond to key messages",
        detail: "Customer follow-up, partnership thread, and team updates.",
        project: null,
        tone: "slate",
        completed: false,
      },
      {
        id: "priority-review",
        group: "Plan Ahead",
        time: "4:30 PM – 5:30 PM",
        title: "Weekly review and next week’s plan",
        detail: "Close the loop and set priorities.",
        project: null,
        tone: "slate",
        completed: false,
      },
    ],
    schedule: [
      { time: "8:30 AM", title: "Coffee & plan", duration: "30 min", tone: "muted" },
      { time: "9:00 AM", title: "Deep work", detail: "Product Forge", duration: "2 hr", tone: "amber" },
      { time: "11:00 AM", title: "Project review", detail: "Device MCP", duration: "2 hr", tone: "teal" },
      { time: "1:00 PM", title: "Lunch", duration: "1 hr", tone: "muted" },
      { time: "2:00 PM", title: "Messages & sync", duration: "1 hr", tone: "muted" },
      { time: "3:30 PM", title: "Monroe Eve planning", duration: "1 hr", tone: "blue" },
      { time: "4:30 PM", title: "Weekly review", duration: "1 hr", tone: "muted" },
    ],
    queue: [
      {
        id: "weekly-brief",
        kind: "assistant",
        title: "Prepare weekly project brief",
        description: "Summarize progress, risks, and next steps across all projects.",
        elapsed: "12m elapsed",
        status: "Control plane — no sandbox",
      },
      {
        id: "device-enrollment",
        kind: "coding",
        title: "Harden Device MCP enrollment",
        description: "Implement retry logic, improve error handling, add tests, and open a PR.",
        elapsed: "28m elapsed",
        status: "Vercel Sandbox — PR approval required",
        phase: 2,
      },
    ],
    memories: [
      { icon: "FileText", title: "Device MCP", detail: "Enrollment reliability work in progress. Focusing on error handling and tests." },
      { icon: "Code", title: "Product Forge", detail: "Onboarding flow nearly complete. Polish copy and ship for internal beta." },
      { icon: "Stack", title: "Monroe Eve", detail: "Planning private alpha. Ingest pipeline performance improved." },
    ],
    workingMemoryUpdatedAt: new Date().toISOString(),
  };
}
